const linkedinProfileLink = [
  {
    name: "Dan Pocock",
    image: "../images/linkedin_profile/Dan_Pocock.jpg",
    link: "https://www.linkedin.com/in/danpocock/",
  },
  {
    name: "Mike Velasco",
    image: "../images/linkedin_profile/Mike_Velasco",
    link: "https://www.linkedin.com/in/mike-velasco-148b5a50/",
  },
  {
    name: "Evan Eliason",
    image: "../images/linkedin_profile/Evan_Elison.jpg",
    link: "https://www.linkedin.com/in/evan-eliason/",
  },
  {
    name: "Yi Hui Lin",
    image: "../images/linkedin_profile/Yi_Hui_Lin.jpg",
    link: "www.linkedin.com/in/yihuilinrosa",
  },
];

const cityInfo = [
  {
    city: "Atlanta",
    state: "GA",
    image: "../images/cities_images/atlanta.jpg",
    todo1: "1. Georgia Aquarium",
    todo2: "2. World of Coca-Cola",
    todo3: "3. Zoo Atlanta",
    todo4: "4. Fernbank Museum of Natural History",
    todo5: "5. College Football Hall of Fame",
    todo6: "6. National Center for Civil and Human Rights",
    cityLink: "https://www.citypass.com/atlanta",
  },
  {
    city: "Chicago",
    state: "IL",
    image: "../images/cities_images/chicago.jpg",
    todo1: "1. Skydeck Chicago",
    todo2: "2. Field Museum",
    todo3: "3. 360 CHICAGO Observation Deck",
    todo4: "4. Adler Planetarium",
    todo5: "5. Art Institute of Chicago",
    todo6: "6. Centennial Ferris Wheel at Navy Pier",
    cityLink: "https://www.citypass.com/chicago-comparison",
  },
  {
    city: "Dallas",
    state: "TX",
    image: "../images/cities_images/dallas.jpg",
    todo1: "1. Perot Museum of Nature and Science",
    todo2: "2. Reunion Tower GeO-Deck",
    todo3: "3. Dallas Zoo",
    todo4: "4. George W. Bush Presidential Museum",
    todo5: "5. Dallas Holocaust and Human Rights Museum",
    todo6: "",
    cityLink: "https://www.citypass.com/dallas",
  },
  {
    city: "Denver",
    state: "CO",
    image: "../images/cities_images/denver.jpg",
    todo1: "1. Denver Downtown Aquarium",
    todo2: "2. Denver Museum of Nature & Science",
    todo3: "3. Denver Botanic Gardens",
    todo4: "4. Children's Museum of Denver at Marsico Campus",
    todo5: "5. Wings Over the Rockies™ Air & Space Museum",
    todo6: "6. Denver Art Museum",
    cityLink: "https://www.citypass.com/denver",
  },
  {
    city: "Los Angeles",
    state: "CA",
    image: "../images/cities_images/los-angeles-1.jpg",
    todo1: "1. Disneyland® Resort",
    todo2: "2. Universal Studios Hollywood™",
    todo3: "3. SeaWorld®",
    todo4: "4. LEGOLAND® California Resort",
    todo5: "",
    todo6: "",
    cityLink: "https://www.citypass.com/southern-california",
  },
  {
    city: "New York City",
    state: "NY",
    image: "../images/cities_images/new-york.jpg",
    todo1: "1. Top of the Rock Observation Deck",
    todo2: "2. Circle Line Sightseeing Cruisesa",
    todo3: "3. The Museum of Modern Art (MoMA)",
    todo4: "4. Edge at Hudson Yards",
    todo5: "5. Intrepid Museum",
    todo6: "6. 9/11 Memorial & Museum",
    cityLink: "https://www.citypass.com/new-york-comparison",
  },
  {
    city: "Seattle",
    state: "WA",
    image: "../images/cities_images/seattle.jpg",
    todo1: "1. Space Needle",
    todo2: "2. Chihuly Garden and Glass",
    todo3: "3. Argosy Cruises Harbor Tour",
    todo4: "4. Museum of Pop Culture (MoPOP)",
    todo5: "5. Pacific Science Center",
    todo6: "6. Sky View Observatory",
    cityLink: "https://www.citypass.com/seattle-comparison",
  },
  {
    city: "Tampa-bay",
    state: "FL",
    image: "../images/cities_images/tempa-bay.jpg",
    todo1: "1. The Tropics Boat Tours (Dolphin Tour OR Sunset Cruise)",
    todo2: "2. Clearwater Marine Aquarium",
    todo3: "3. Museum of Science & Industry",
    todo4: "4. Glazer Children's Museum",
    todo5: "",
    todo6: "",
    cityLink: "https://www.citypass.com/tampa",
  },
];

/* -------------------------------------------------------------------------- */
/*                                 citiesCard                                 */
/* -------------------------------------------------------------------------- */
